### ISSUE TITLE
Database preparation

### ISSUE THREAD

**Issue by sarah872** [kbseah/tcdbparse_sqlite#3]
I am trying to run the database preparation with
`perl tcdbparse_sqlite.pl -task setup -db template_database.sqlite -tcfam tc_family_names.tsv`

but I get the error
`Please supply shortlist of uptake transporters at tcdbparse_sqlite.pl line 163.`

Where can I get this file from?
Is there a way to generate/update it myself (including the `tc_family_names.tsv`?

**Comment by kbseah** [comment]
Hello @sarah872 : The shortlist should be a subset of the file `tc_family_names.tsv`, which you would choose yourself based on your own criteria. The path to the file should then be specified with the option `-uptake`. This script was written for my own research and I wasn't expecting anyone else to try using it, so I'm sorry that it is somewhat cryptic. Hope that this helps
